---
ocloud_infra: vm
ocloud_platform: okd
ocloud_topology: aio
ocloud_platform_okd_ssh_pubkey: ~
ocloud_cluster_name: "ocloud-vm-bmw"
ocloud_domain_name: "lab.local"

ocloud_infra_vm_net_network_mode: "bridge"
ocloud_infra_vm_net_bridge: "bridge0"
ocloud_net_name: "br0-okd"

ocloud_net_cidr: "192.168.8.0/24"
ocloud_cluster_net_cidr: "10.128.0.0/14"
ocloud_cluster_net_hostprefix: 23
ocloud_service_net_cidr: "172.30.0.0/16"
ocloud_infra_vm_net_bridge: "OVNKubernetes"

# DNS servers
ocloud_dns_servers:
  - "192.168.8.72"

# Optional NTP servers
ocloud_ntp_servers:
  - "time.google.com"
