---
ocloud_platform_stolostron_pull_secret: "{{ ocloud_platform_okd_pull_secret }}"
ocloud_kubeconfig: ~
ocloud_platform_stolostron_snapshot: "2.15.0-SNAPSHOT-2025-09-08-23-25-39"
ocloud_platform_stolostron_repo_url: "https://github.com/stolostron/deploy.git"
