---
ocloud_infra: vm
ocloud_platform: okd
ocloud_topology: aio
ocloud_cluster_name: "ocloud-vm-okd-aio"
ocloud_domain_name: "lab.local" 

ocloud_net_cidr: "192.168.100.0/24"
ocloud_cluster_net_cidr: "10.128.0.0/14"
ocloud_cluster_net_hostprefix: 23
ocloud_service_net_cidr: "172.30.0.0/16"
ocloud_network_type: "OVNKubernetes"

ocloud_dns_servers:
  - "8.8.8.8"
  - "1.1.1.1"

ocloud_ntp_servers:
  - "time.google.com"
