apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterinstance-defaults-v1
  namespace: sno-du-okd-v4-19
data:
  clusterInstallationTimeout: "90m"
  clusterinstance-defaults: |
    baseDomain: example.com
    clusterType: SNO
    clusterImageSetNameRef: "4.19.0-okd-scos.19"
    pullSecretRef:
      name: pull-secret
    networkType: OVNKubernetes
    sshPublicKey: ssh-rsa xxxxxxxxxxx
    installConfigOverrides: '{"capabilities": {"baselineCapabilitySet": "None", "additionalEnabledCapabilities": ["NodeTuning", "OperatorLifecycleManager", "Ingress"]}}'
    ignitionConfigOverride: '{"ignition": {"version": "3.2.0"}, "storage": {"files": [{"overwrite": true, "path": "/etc/containers/policy.json", "contents": {"source":"data:text/plain;base64,ewogICAgImRlZmF1bHQiOiBbCiAgICAgICAgewogICAgICAgICAgICAidHlwZSI6ICJpbnNlY3VyZUFjY2VwdEFueXRoaW5nIgogICAgICAgIH0KICAgIF0sCiAgICAidHJhbnNwb3J0cyI6CiAgICAgICAgewogICAgICAgICAgICAiZG9ja2VyLWRhZW1vbiI6CiAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgIiI6IFt7InR5cGUiOiJpbnNlY3VyZUFjY2VwdEFueXRoaW5nIn1dCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cgo="}}]}}'
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.123.0/24
    serviceNetwork:
      - cidr: 172.30.0.0/16
    additionalNTPSources:
      - 1.pool.ntp.org
    templateRefs:
      - name: ai-cluster-templates-v1
        namespace: open-cluster-management
    cpuPartitioningMode: AllNodes
    extraManifestsRefs:
      - name: okd.v1.0.0-extramanifests
    nodes:
      - role: master
        bootMode: UEFI
        rootDeviceHints:
          deviceName: /dev/sda
        nodeNetwork:
          interfaces:
            - name: ens1f0
              label: bootable-interface
          config:
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: ens1f0
                  table-id: 254
            interfaces:
              - ipv6:
                  enabled: false
                ipv4:
                  enabled: true
                name: ens1f0
                state: up
                type: ethernet
        templateRefs:
          - name: ai-node-templates-v1
            namespace: open-cluster-management
