---
ocloud_infra_vm_cpus: 16
ocloud_infra_vm_mem_gb: 32
ocloud_infra_vm_disk_gb: 150
ocloud_infra_vm_disk_dir: "/var/lib/libvirt/images"
ocloud_infra_vm_disk_path: "{{ ocloud_infra_vm_disk_dir }}/{{ inventory_hostname }}.qcow2"
ocloud_infra_vm_image: "{{ ocloud_infra_vm_disk_dir }}/{{ inventory_hostname }}-image.iso"
ocloud_net_name: "ocloud"
ocloud_infra_vm_net_bridge: "ocloud-br"
ocloud_net_mac_prefix: "52:54:00:01:23"
ocloud_infra_vm_net_mode: "nat"
