---
ocloud_compliance_deployment_manager: ~
ocloud_compliance_repo: "https://gerrit.o-ran-sc.org/r/it/test.git"
ocloud_compliance_o2ims_port: 443
ocloud_compliance_o2ims_protocol: https
ocloud_compliance_ocloud_id: ~
ocloud_compliance_location_id: ~
ocloud_compliance_resource_type: ~
ocloud_compliance_resource_desc_substring: ~
ocloud_compliance_ssh_host: localhost
ocloud_compliance_ssh_port: 22
ocloud_compliance_ssh_user: robot
ocloud_compliance_ssh_password: robot
ocloud_compliance_smo_host: "{{ ansible_default_ipv4['address'] }}"
ocloud_compliance_smo_port: 1080
ocloud_compliance_smo_protocol: https
ocloud_compliance_notification_endpoint: ~
ocloud_compliance_notification_resource_address: ~
ocloud_compliance_notification_publisher_endpoint: ~
